/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WidgetDotjsRouteImport } from './routes/widget[.]js'
import { Route as VendasRouteImport } from './routes/vendas'
import { Route as SuporteRouteImport } from './routes/suporte'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PipelinesRouteImport } from './routes/pipelines'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DefinirSenhaRouteImport } from './routes/definir-senha'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PipelinesIndexRouteImport } from './routes/pipelines.index'
import { Route as PipelinesIdRouteImport } from './routes/pipelines.$id'
import { Route as AdminUsuariosRouteImport } from './routes/admin/usuarios'
import { Route as AdminTemplatesRouteImport } from './routes/admin/templates'
import { Route as AdminStressTestRouteImport } from './routes/admin/stress-test'
import { Route as AdminRastreioRouteImport } from './routes/admin/rastreio'
import { Route as AdminMarcasRouteImport } from './routes/admin/marcas'
import { Route as AdminIntegracoesRouteImport } from './routes/admin/integracoes'
import { Route as AdminFilasRouteImport } from './routes/admin/filas'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminCopilotRouteImport } from './routes/admin/copilot'
import { Route as AdminContatosRouteImport } from './routes/admin/contatos'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin/configuracoes'
import { Route as AdminBlocklistRouteImport } from './routes/admin/blocklist'
import { Route as AdminBasesConhecimentoRouteImport } from './routes/admin/bases-conhecimento'
import { Route as AdminApiLogsRouteImport } from './routes/admin/api-logs'
import { Route as AdminApiKeysRouteImport } from './routes/admin/api-keys'
import { Route as AdminAgendaRouteImport } from './routes/admin/agenda'
import { Route as AdminContatosIndexRouteImport } from './routes/admin/contatos.index'
import { Route as AdminBroadcastsIndexRouteImport } from './routes/admin/broadcasts.index'
import { Route as AdminAutomacoesIndexRouteImport } from './routes/admin/automacoes.index'
import { Route as AdminAgentesIndexRouteImport } from './routes/admin/agentes.index'
import { Route as ApiPublicCopilotChatRouteImport } from './routes/api/public/copilot-chat'
import { Route as AdminWebchatPreviewWidgetIdRouteImport } from './routes/admin/webchat-preview.$widgetId'
import { Route as AdminEllieValidationsRouteImport } from './routes/admin/ellie.validations'
import { Route as AdminContatosImportacoesRouteImport } from './routes/admin/contatos.importacoes'
import { Route as AdminBroadcastsIdRouteImport } from './routes/admin/broadcasts.$id'
import { Route as AdminAutomacoesRunsRouteImport } from './routes/admin/automacoes.runs'
import { Route as AdminAutomacoesIdRouteImport } from './routes/admin/automacoes.$id'
import { Route as AdminAgentesIdRouteImport } from './routes/admin/agentes.$id'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicV1OpenapiDotjsonRouteImport } from './routes/api/public/v1/openapi[.]json'
import { Route as ApiPublicV1DocsRouteImport } from './routes/api/public/v1/docs'
import { Route as ApiPublicV1ContactsRouteImport } from './routes/api/public/v1/contacts'
import { Route as ApiPublicHooksAutomationTickRouteImport } from './routes/api/public/hooks/automation-tick'
import { Route as ApiPublicCronPipelineActivitiesTickRouteImport } from './routes/api/public/cron/pipeline-activities-tick'
import { Route as ApiPublicCronIntegrationsPollRouteImport } from './routes/api/public/cron/integrations-poll'
import { Route as ApiPublicCronIntegrationsDrainRouteImport } from './routes/api/public/cron/integrations-drain'
import { Route as ApiPublicCronContactImportsDrainRouteImport } from './routes/api/public/cron/contact-imports-drain'
import { Route as ApiPublicCronBroadcastTickRouteImport } from './routes/api/public/cron/broadcast-tick'
import { Route as ApiPublicCronBroadcastReconcileRouteImport } from './routes/api/public/cron/broadcast-reconcile'
import { Route as ApiPublicCronBroadcastLoopRouteImport } from './routes/api/public/cron/broadcast-loop'
import { Route as ApiPublicCronBroadcastDrainRouteImport } from './routes/api/public/cron/broadcast-drain'
import { Route as ApiPublicCronAiAgentsDrainRouteImport } from './routes/api/public/cron/ai-agents-drain'
import { Route as ApiPublicWebhooksShopifyAccountIdRouteImport } from './routes/api/public/webhooks/shopify.$accountId'
import { Route as ApiPublicWebhooksSendflowAccountIdRouteImport } from './routes/api/public/webhooks/sendflow.$accountId'
import { Route as ApiPublicWebhooksHotmartAccountIdRouteImport } from './routes/api/public/webhooks/hotmart.$accountId'
import { Route as ApiPublicWebhooksActivecampaignAccountIdRouteImport } from './routes/api/public/webhooks/activecampaign.$accountId'
import { Route as ApiPublicWebchatWidgetIdUploadRouteImport } from './routes/api/public/webchat.$widgetId.upload'
import { Route as ApiPublicWebchatWidgetIdSessionRouteImport } from './routes/api/public/webchat.$widgetId.session'
import { Route as ApiPublicWebchatWidgetIdMessagesRouteImport } from './routes/api/public/webchat.$widgetId.messages'
import { Route as ApiPublicWebchatWidgetIdConfigRouteImport } from './routes/api/public/webchat.$widgetId.config'
import { Route as ApiPublicV1ContactsIdRouteImport } from './routes/api/public/v1/contacts.$id'
import { Route as ApiPublicV1ContactsIdTagsRouteImport } from './routes/api/public/v1/contacts.$id.tags'
import { Route as ApiPublicV1AutomationsIdTriggerRouteImport } from './routes/api/public/v1/automations.$id.trigger'

const WidgetDotjsRoute = WidgetDotjsRouteImport.update({
  id: '/widget.js',
  path: '/widget.js',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasRoute = VendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelinesRoute = PipelinesRouteImport.update({
  id: '/pipelines',
  path: '/pipelines',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DefinirSenhaRoute = DefinirSenhaRouteImport.update({
  id: '/definir-senha',
  path: '/definir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelinesIndexRoute = PipelinesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PipelinesRoute,
} as any)
const PipelinesIdRoute = PipelinesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PipelinesRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/admin/usuarios',
  path: '/admin/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTemplatesRoute = AdminTemplatesRouteImport.update({
  id: '/admin/templates',
  path: '/admin/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStressTestRoute = AdminStressTestRouteImport.update({
  id: '/admin/stress-test',
  path: '/admin/stress-test',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRastreioRoute = AdminRastreioRouteImport.update({
  id: '/admin/rastreio',
  path: '/admin/rastreio',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMarcasRoute = AdminMarcasRouteImport.update({
  id: '/admin/marcas',
  path: '/admin/marcas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIntegracoesRoute = AdminIntegracoesRouteImport.update({
  id: '/admin/integracoes',
  path: '/admin/integracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFilasRoute = AdminFilasRouteImport.update({
  id: '/admin/filas',
  path: '/admin/filas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCopilotRoute = AdminCopilotRouteImport.update({
  id: '/admin/copilot',
  path: '/admin/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContatosRoute = AdminContatosRouteImport.update({
  id: '/admin/contatos',
  path: '/admin/contatos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/admin/configuracoes',
  path: '/admin/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlocklistRoute = AdminBlocklistRouteImport.update({
  id: '/admin/blocklist',
  path: '/admin/blocklist',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBasesConhecimentoRoute = AdminBasesConhecimentoRouteImport.update({
  id: '/admin/bases-conhecimento',
  path: '/admin/bases-conhecimento',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApiLogsRoute = AdminApiLogsRouteImport.update({
  id: '/admin/api-logs',
  path: '/admin/api-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApiKeysRoute = AdminApiKeysRouteImport.update({
  id: '/admin/api-keys',
  path: '/admin/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAgendaRoute = AdminAgendaRouteImport.update({
  id: '/admin/agenda',
  path: '/admin/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContatosIndexRoute = AdminContatosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminContatosRoute,
} as any)
const AdminBroadcastsIndexRoute = AdminBroadcastsIndexRouteImport.update({
  id: '/admin/broadcasts/',
  path: '/admin/broadcasts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAutomacoesIndexRoute = AdminAutomacoesIndexRouteImport.update({
  id: '/admin/automacoes/',
  path: '/admin/automacoes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAgentesIndexRoute = AdminAgentesIndexRouteImport.update({
  id: '/admin/agentes/',
  path: '/admin/agentes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCopilotChatRoute = ApiPublicCopilotChatRouteImport.update({
  id: '/api/public/copilot-chat',
  path: '/api/public/copilot-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWebchatPreviewWidgetIdRoute =
  AdminWebchatPreviewWidgetIdRouteImport.update({
    id: '/admin/webchat-preview/$widgetId',
    path: '/admin/webchat-preview/$widgetId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminEllieValidationsRoute = AdminEllieValidationsRouteImport.update({
  id: '/admin/ellie/validations',
  path: '/admin/ellie/validations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContatosImportacoesRoute =
  AdminContatosImportacoesRouteImport.update({
    id: '/importacoes',
    path: '/importacoes',
    getParentRoute: () => AdminContatosRoute,
  } as any)
const AdminBroadcastsIdRoute = AdminBroadcastsIdRouteImport.update({
  id: '/admin/broadcasts/$id',
  path: '/admin/broadcasts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAutomacoesRunsRoute = AdminAutomacoesRunsRouteImport.update({
  id: '/admin/automacoes/runs',
  path: '/admin/automacoes/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAutomacoesIdRoute = AdminAutomacoesIdRouteImport.update({
  id: '/admin/automacoes/$id',
  path: '/admin/automacoes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAgentesIdRoute = AdminAgentesIdRouteImport.update({
  id: '/admin/agentes/$id',
  path: '/admin/agentes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1OpenapiDotjsonRoute =
  ApiPublicV1OpenapiDotjsonRouteImport.update({
    id: '/api/public/v1/openapi.json',
    path: '/api/public/v1/openapi.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1DocsRoute = ApiPublicV1DocsRouteImport.update({
  id: '/api/public/v1/docs',
  path: '/api/public/v1/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ContactsRoute = ApiPublicV1ContactsRouteImport.update({
  id: '/api/public/v1/contacts',
  path: '/api/public/v1/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksAutomationTickRoute =
  ApiPublicHooksAutomationTickRouteImport.update({
    id: '/api/public/hooks/automation-tick',
    path: '/api/public/hooks/automation-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronPipelineActivitiesTickRoute =
  ApiPublicCronPipelineActivitiesTickRouteImport.update({
    id: '/api/public/cron/pipeline-activities-tick',
    path: '/api/public/cron/pipeline-activities-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronIntegrationsPollRoute =
  ApiPublicCronIntegrationsPollRouteImport.update({
    id: '/api/public/cron/integrations-poll',
    path: '/api/public/cron/integrations-poll',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronIntegrationsDrainRoute =
  ApiPublicCronIntegrationsDrainRouteImport.update({
    id: '/api/public/cron/integrations-drain',
    path: '/api/public/cron/integrations-drain',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronContactImportsDrainRoute =
  ApiPublicCronContactImportsDrainRouteImport.update({
    id: '/api/public/cron/contact-imports-drain',
    path: '/api/public/cron/contact-imports-drain',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronBroadcastTickRoute =
  ApiPublicCronBroadcastTickRouteImport.update({
    id: '/api/public/cron/broadcast-tick',
    path: '/api/public/cron/broadcast-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronBroadcastReconcileRoute =
  ApiPublicCronBroadcastReconcileRouteImport.update({
    id: '/api/public/cron/broadcast-reconcile',
    path: '/api/public/cron/broadcast-reconcile',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronBroadcastLoopRoute =
  ApiPublicCronBroadcastLoopRouteImport.update({
    id: '/api/public/cron/broadcast-loop',
    path: '/api/public/cron/broadcast-loop',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronBroadcastDrainRoute =
  ApiPublicCronBroadcastDrainRouteImport.update({
    id: '/api/public/cron/broadcast-drain',
    path: '/api/public/cron/broadcast-drain',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronAiAgentsDrainRoute =
  ApiPublicCronAiAgentsDrainRouteImport.update({
    id: '/api/public/cron/ai-agents-drain',
    path: '/api/public/cron/ai-agents-drain',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksShopifyAccountIdRoute =
  ApiPublicWebhooksShopifyAccountIdRouteImport.update({
    id: '/api/public/webhooks/shopify/$accountId',
    path: '/api/public/webhooks/shopify/$accountId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksSendflowAccountIdRoute =
  ApiPublicWebhooksSendflowAccountIdRouteImport.update({
    id: '/api/public/webhooks/sendflow/$accountId',
    path: '/api/public/webhooks/sendflow/$accountId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksHotmartAccountIdRoute =
  ApiPublicWebhooksHotmartAccountIdRouteImport.update({
    id: '/api/public/webhooks/hotmart/$accountId',
    path: '/api/public/webhooks/hotmart/$accountId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksActivecampaignAccountIdRoute =
  ApiPublicWebhooksActivecampaignAccountIdRouteImport.update({
    id: '/api/public/webhooks/activecampaign/$accountId',
    path: '/api/public/webhooks/activecampaign/$accountId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebchatWidgetIdUploadRoute =
  ApiPublicWebchatWidgetIdUploadRouteImport.update({
    id: '/api/public/webchat/$widgetId/upload',
    path: '/api/public/webchat/$widgetId/upload',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebchatWidgetIdSessionRoute =
  ApiPublicWebchatWidgetIdSessionRouteImport.update({
    id: '/api/public/webchat/$widgetId/session',
    path: '/api/public/webchat/$widgetId/session',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebchatWidgetIdMessagesRoute =
  ApiPublicWebchatWidgetIdMessagesRouteImport.update({
    id: '/api/public/webchat/$widgetId/messages',
    path: '/api/public/webchat/$widgetId/messages',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebchatWidgetIdConfigRoute =
  ApiPublicWebchatWidgetIdConfigRouteImport.update({
    id: '/api/public/webchat/$widgetId/config',
    path: '/api/public/webchat/$widgetId/config',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1ContactsIdRoute = ApiPublicV1ContactsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPublicV1ContactsRoute,
} as any)
const ApiPublicV1ContactsIdTagsRoute =
  ApiPublicV1ContactsIdTagsRouteImport.update({
    id: '/tags',
    path: '/tags',
    getParentRoute: () => ApiPublicV1ContactsIdRoute,
  } as any)
const ApiPublicV1AutomationsIdTriggerRoute =
  ApiPublicV1AutomationsIdTriggerRouteImport.update({
    id: '/api/public/v1/automations/$id/trigger',
    path: '/api/public/v1/automations/$id/trigger',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/definir-senha': typeof DefinirSenhaRoute
  '/docs': typeof DocsRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/pipelines': typeof PipelinesRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/suporte': typeof SuporteRoute
  '/vendas': typeof VendasRoute
  '/widget.js': typeof WidgetDotjsRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/api-logs': typeof AdminApiLogsRoute
  '/admin/bases-conhecimento': typeof AdminBasesConhecimentoRoute
  '/admin/blocklist': typeof AdminBlocklistRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/contatos': typeof AdminContatosRouteWithChildren
  '/admin/copilot': typeof AdminCopilotRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/filas': typeof AdminFilasRoute
  '/admin/integracoes': typeof AdminIntegracoesRoute
  '/admin/marcas': typeof AdminMarcasRoute
  '/admin/rastreio': typeof AdminRastreioRoute
  '/admin/stress-test': typeof AdminStressTestRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/pipelines/$id': typeof PipelinesIdRoute
  '/pipelines/': typeof PipelinesIndexRoute
  '/admin/agentes/$id': typeof AdminAgentesIdRoute
  '/admin/automacoes/$id': typeof AdminAutomacoesIdRoute
  '/admin/automacoes/runs': typeof AdminAutomacoesRunsRoute
  '/admin/broadcasts/$id': typeof AdminBroadcastsIdRoute
  '/admin/contatos/importacoes': typeof AdminContatosImportacoesRoute
  '/admin/ellie/validations': typeof AdminEllieValidationsRoute
  '/admin/webchat-preview/$widgetId': typeof AdminWebchatPreviewWidgetIdRoute
  '/api/public/copilot-chat': typeof ApiPublicCopilotChatRoute
  '/admin/agentes/': typeof AdminAgentesIndexRoute
  '/admin/automacoes/': typeof AdminAutomacoesIndexRoute
  '/admin/broadcasts/': typeof AdminBroadcastsIndexRoute
  '/admin/contatos/': typeof AdminContatosIndexRoute
  '/api/public/cron/ai-agents-drain': typeof ApiPublicCronAiAgentsDrainRoute
  '/api/public/cron/broadcast-drain': typeof ApiPublicCronBroadcastDrainRoute
  '/api/public/cron/broadcast-loop': typeof ApiPublicCronBroadcastLoopRoute
  '/api/public/cron/broadcast-reconcile': typeof ApiPublicCronBroadcastReconcileRoute
  '/api/public/cron/broadcast-tick': typeof ApiPublicCronBroadcastTickRoute
  '/api/public/cron/contact-imports-drain': typeof ApiPublicCronContactImportsDrainRoute
  '/api/public/cron/integrations-drain': typeof ApiPublicCronIntegrationsDrainRoute
  '/api/public/cron/integrations-poll': typeof ApiPublicCronIntegrationsPollRoute
  '/api/public/cron/pipeline-activities-tick': typeof ApiPublicCronPipelineActivitiesTickRoute
  '/api/public/hooks/automation-tick': typeof ApiPublicHooksAutomationTickRoute
  '/api/public/v1/contacts': typeof ApiPublicV1ContactsRouteWithChildren
  '/api/public/v1/docs': typeof ApiPublicV1DocsRoute
  '/api/public/v1/openapi.json': typeof ApiPublicV1OpenapiDotjsonRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/api/public/v1/contacts/$id': typeof ApiPublicV1ContactsIdRouteWithChildren
  '/api/public/webchat/$widgetId/config': typeof ApiPublicWebchatWidgetIdConfigRoute
  '/api/public/webchat/$widgetId/messages': typeof ApiPublicWebchatWidgetIdMessagesRoute
  '/api/public/webchat/$widgetId/session': typeof ApiPublicWebchatWidgetIdSessionRoute
  '/api/public/webchat/$widgetId/upload': typeof ApiPublicWebchatWidgetIdUploadRoute
  '/api/public/webhooks/activecampaign/$accountId': typeof ApiPublicWebhooksActivecampaignAccountIdRoute
  '/api/public/webhooks/hotmart/$accountId': typeof ApiPublicWebhooksHotmartAccountIdRoute
  '/api/public/webhooks/sendflow/$accountId': typeof ApiPublicWebhooksSendflowAccountIdRoute
  '/api/public/webhooks/shopify/$accountId': typeof ApiPublicWebhooksShopifyAccountIdRoute
  '/api/public/v1/automations/$id/trigger': typeof ApiPublicV1AutomationsIdTriggerRoute
  '/api/public/v1/contacts/$id/tags': typeof ApiPublicV1ContactsIdTagsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/definir-senha': typeof DefinirSenhaRoute
  '/docs': typeof DocsRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/suporte': typeof SuporteRoute
  '/vendas': typeof VendasRoute
  '/widget.js': typeof WidgetDotjsRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/api-logs': typeof AdminApiLogsRoute
  '/admin/bases-conhecimento': typeof AdminBasesConhecimentoRoute
  '/admin/blocklist': typeof AdminBlocklistRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/copilot': typeof AdminCopilotRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/filas': typeof AdminFilasRoute
  '/admin/integracoes': typeof AdminIntegracoesRoute
  '/admin/marcas': typeof AdminMarcasRoute
  '/admin/rastreio': typeof AdminRastreioRoute
  '/admin/stress-test': typeof AdminStressTestRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/pipelines/$id': typeof PipelinesIdRoute
  '/pipelines': typeof PipelinesIndexRoute
  '/admin/agentes/$id': typeof AdminAgentesIdRoute
  '/admin/automacoes/$id': typeof AdminAutomacoesIdRoute
  '/admin/automacoes/runs': typeof AdminAutomacoesRunsRoute
  '/admin/broadcasts/$id': typeof AdminBroadcastsIdRoute
  '/admin/contatos/importacoes': typeof AdminContatosImportacoesRoute
  '/admin/ellie/validations': typeof AdminEllieValidationsRoute
  '/admin/webchat-preview/$widgetId': typeof AdminWebchatPreviewWidgetIdRoute
  '/api/public/copilot-chat': typeof ApiPublicCopilotChatRoute
  '/admin/agentes': typeof AdminAgentesIndexRoute
  '/admin/automacoes': typeof AdminAutomacoesIndexRoute
  '/admin/broadcasts': typeof AdminBroadcastsIndexRoute
  '/admin/contatos': typeof AdminContatosIndexRoute
  '/api/public/cron/ai-agents-drain': typeof ApiPublicCronAiAgentsDrainRoute
  '/api/public/cron/broadcast-drain': typeof ApiPublicCronBroadcastDrainRoute
  '/api/public/cron/broadcast-loop': typeof ApiPublicCronBroadcastLoopRoute
  '/api/public/cron/broadcast-reconcile': typeof ApiPublicCronBroadcastReconcileRoute
  '/api/public/cron/broadcast-tick': typeof ApiPublicCronBroadcastTickRoute
  '/api/public/cron/contact-imports-drain': typeof ApiPublicCronContactImportsDrainRoute
  '/api/public/cron/integrations-drain': typeof ApiPublicCronIntegrationsDrainRoute
  '/api/public/cron/integrations-poll': typeof ApiPublicCronIntegrationsPollRoute
  '/api/public/cron/pipeline-activities-tick': typeof ApiPublicCronPipelineActivitiesTickRoute
  '/api/public/hooks/automation-tick': typeof ApiPublicHooksAutomationTickRoute
  '/api/public/v1/contacts': typeof ApiPublicV1ContactsRouteWithChildren
  '/api/public/v1/docs': typeof ApiPublicV1DocsRoute
  '/api/public/v1/openapi.json': typeof ApiPublicV1OpenapiDotjsonRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/api/public/v1/contacts/$id': typeof ApiPublicV1ContactsIdRouteWithChildren
  '/api/public/webchat/$widgetId/config': typeof ApiPublicWebchatWidgetIdConfigRoute
  '/api/public/webchat/$widgetId/messages': typeof ApiPublicWebchatWidgetIdMessagesRoute
  '/api/public/webchat/$widgetId/session': typeof ApiPublicWebchatWidgetIdSessionRoute
  '/api/public/webchat/$widgetId/upload': typeof ApiPublicWebchatWidgetIdUploadRoute
  '/api/public/webhooks/activecampaign/$accountId': typeof ApiPublicWebhooksActivecampaignAccountIdRoute
  '/api/public/webhooks/hotmart/$accountId': typeof ApiPublicWebhooksHotmartAccountIdRoute
  '/api/public/webhooks/sendflow/$accountId': typeof ApiPublicWebhooksSendflowAccountIdRoute
  '/api/public/webhooks/shopify/$accountId': typeof ApiPublicWebhooksShopifyAccountIdRoute
  '/api/public/v1/automations/$id/trigger': typeof ApiPublicV1AutomationsIdTriggerRoute
  '/api/public/v1/contacts/$id/tags': typeof ApiPublicV1ContactsIdTagsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/definir-senha': typeof DefinirSenhaRoute
  '/docs': typeof DocsRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/pipelines': typeof PipelinesRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/suporte': typeof SuporteRoute
  '/vendas': typeof VendasRoute
  '/widget.js': typeof WidgetDotjsRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/api-keys': typeof AdminApiKeysRoute
  '/admin/api-logs': typeof AdminApiLogsRoute
  '/admin/bases-conhecimento': typeof AdminBasesConhecimentoRoute
  '/admin/blocklist': typeof AdminBlocklistRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/contatos': typeof AdminContatosRouteWithChildren
  '/admin/copilot': typeof AdminCopilotRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/filas': typeof AdminFilasRoute
  '/admin/integracoes': typeof AdminIntegracoesRoute
  '/admin/marcas': typeof AdminMarcasRoute
  '/admin/rastreio': typeof AdminRastreioRoute
  '/admin/stress-test': typeof AdminStressTestRoute
  '/admin/templates': typeof AdminTemplatesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/pipelines/$id': typeof PipelinesIdRoute
  '/pipelines/': typeof PipelinesIndexRoute
  '/admin/agentes/$id': typeof AdminAgentesIdRoute
  '/admin/automacoes/$id': typeof AdminAutomacoesIdRoute
  '/admin/automacoes/runs': typeof AdminAutomacoesRunsRoute
  '/admin/broadcasts/$id': typeof AdminBroadcastsIdRoute
  '/admin/contatos/importacoes': typeof AdminContatosImportacoesRoute
  '/admin/ellie/validations': typeof AdminEllieValidationsRoute
  '/admin/webchat-preview/$widgetId': typeof AdminWebchatPreviewWidgetIdRoute
  '/api/public/copilot-chat': typeof ApiPublicCopilotChatRoute
  '/admin/agentes/': typeof AdminAgentesIndexRoute
  '/admin/automacoes/': typeof AdminAutomacoesIndexRoute
  '/admin/broadcasts/': typeof AdminBroadcastsIndexRoute
  '/admin/contatos/': typeof AdminContatosIndexRoute
  '/api/public/cron/ai-agents-drain': typeof ApiPublicCronAiAgentsDrainRoute
  '/api/public/cron/broadcast-drain': typeof ApiPublicCronBroadcastDrainRoute
  '/api/public/cron/broadcast-loop': typeof ApiPublicCronBroadcastLoopRoute
  '/api/public/cron/broadcast-reconcile': typeof ApiPublicCronBroadcastReconcileRoute
  '/api/public/cron/broadcast-tick': typeof ApiPublicCronBroadcastTickRoute
  '/api/public/cron/contact-imports-drain': typeof ApiPublicCronContactImportsDrainRoute
  '/api/public/cron/integrations-drain': typeof ApiPublicCronIntegrationsDrainRoute
  '/api/public/cron/integrations-poll': typeof ApiPublicCronIntegrationsPollRoute
  '/api/public/cron/pipeline-activities-tick': typeof ApiPublicCronPipelineActivitiesTickRoute
  '/api/public/hooks/automation-tick': typeof ApiPublicHooksAutomationTickRoute
  '/api/public/v1/contacts': typeof ApiPublicV1ContactsRouteWithChildren
  '/api/public/v1/docs': typeof ApiPublicV1DocsRoute
  '/api/public/v1/openapi.json': typeof ApiPublicV1OpenapiDotjsonRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/api/public/v1/contacts/$id': typeof ApiPublicV1ContactsIdRouteWithChildren
  '/api/public/webchat/$widgetId/config': typeof ApiPublicWebchatWidgetIdConfigRoute
  '/api/public/webchat/$widgetId/messages': typeof ApiPublicWebchatWidgetIdMessagesRoute
  '/api/public/webchat/$widgetId/session': typeof ApiPublicWebchatWidgetIdSessionRoute
  '/api/public/webchat/$widgetId/upload': typeof ApiPublicWebchatWidgetIdUploadRoute
  '/api/public/webhooks/activecampaign/$accountId': typeof ApiPublicWebhooksActivecampaignAccountIdRoute
  '/api/public/webhooks/hotmart/$accountId': typeof ApiPublicWebhooksHotmartAccountIdRoute
  '/api/public/webhooks/sendflow/$accountId': typeof ApiPublicWebhooksSendflowAccountIdRoute
  '/api/public/webhooks/shopify/$accountId': typeof ApiPublicWebhooksShopifyAccountIdRoute
  '/api/public/v1/automations/$id/trigger': typeof ApiPublicV1AutomationsIdTriggerRoute
  '/api/public/v1/contacts/$id/tags': typeof ApiPublicV1ContactsIdTagsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/definir-senha'
    | '/docs'
    | '/inbox'
    | '/login'
    | '/pipelines'
    | '/privacidade'
    | '/suporte'
    | '/vendas'
    | '/widget.js'
    | '/admin/agenda'
    | '/admin/api-keys'
    | '/admin/api-logs'
    | '/admin/bases-conhecimento'
    | '/admin/blocklist'
    | '/admin/configuracoes'
    | '/admin/contatos'
    | '/admin/copilot'
    | '/admin/dashboard'
    | '/admin/filas'
    | '/admin/integracoes'
    | '/admin/marcas'
    | '/admin/rastreio'
    | '/admin/stress-test'
    | '/admin/templates'
    | '/admin/usuarios'
    | '/pipelines/$id'
    | '/pipelines/'
    | '/admin/agentes/$id'
    | '/admin/automacoes/$id'
    | '/admin/automacoes/runs'
    | '/admin/broadcasts/$id'
    | '/admin/contatos/importacoes'
    | '/admin/ellie/validations'
    | '/admin/webchat-preview/$widgetId'
    | '/api/public/copilot-chat'
    | '/admin/agentes/'
    | '/admin/automacoes/'
    | '/admin/broadcasts/'
    | '/admin/contatos/'
    | '/api/public/cron/ai-agents-drain'
    | '/api/public/cron/broadcast-drain'
    | '/api/public/cron/broadcast-loop'
    | '/api/public/cron/broadcast-reconcile'
    | '/api/public/cron/broadcast-tick'
    | '/api/public/cron/contact-imports-drain'
    | '/api/public/cron/integrations-drain'
    | '/api/public/cron/integrations-poll'
    | '/api/public/cron/pipeline-activities-tick'
    | '/api/public/hooks/automation-tick'
    | '/api/public/v1/contacts'
    | '/api/public/v1/docs'
    | '/api/public/v1/openapi.json'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/api/public/v1/contacts/$id'
    | '/api/public/webchat/$widgetId/config'
    | '/api/public/webchat/$widgetId/messages'
    | '/api/public/webchat/$widgetId/session'
    | '/api/public/webchat/$widgetId/upload'
    | '/api/public/webhooks/activecampaign/$accountId'
    | '/api/public/webhooks/hotmart/$accountId'
    | '/api/public/webhooks/sendflow/$accountId'
    | '/api/public/webhooks/shopify/$accountId'
    | '/api/public/v1/automations/$id/trigger'
    | '/api/public/v1/contacts/$id/tags'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/definir-senha'
    | '/docs'
    | '/inbox'
    | '/login'
    | '/privacidade'
    | '/suporte'
    | '/vendas'
    | '/widget.js'
    | '/admin/agenda'
    | '/admin/api-keys'
    | '/admin/api-logs'
    | '/admin/bases-conhecimento'
    | '/admin/blocklist'
    | '/admin/configuracoes'
    | '/admin/copilot'
    | '/admin/dashboard'
    | '/admin/filas'
    | '/admin/integracoes'
    | '/admin/marcas'
    | '/admin/rastreio'
    | '/admin/stress-test'
    | '/admin/templates'
    | '/admin/usuarios'
    | '/pipelines/$id'
    | '/pipelines'
    | '/admin/agentes/$id'
    | '/admin/automacoes/$id'
    | '/admin/automacoes/runs'
    | '/admin/broadcasts/$id'
    | '/admin/contatos/importacoes'
    | '/admin/ellie/validations'
    | '/admin/webchat-preview/$widgetId'
    | '/api/public/copilot-chat'
    | '/admin/agentes'
    | '/admin/automacoes'
    | '/admin/broadcasts'
    | '/admin/contatos'
    | '/api/public/cron/ai-agents-drain'
    | '/api/public/cron/broadcast-drain'
    | '/api/public/cron/broadcast-loop'
    | '/api/public/cron/broadcast-reconcile'
    | '/api/public/cron/broadcast-tick'
    | '/api/public/cron/contact-imports-drain'
    | '/api/public/cron/integrations-drain'
    | '/api/public/cron/integrations-poll'
    | '/api/public/cron/pipeline-activities-tick'
    | '/api/public/hooks/automation-tick'
    | '/api/public/v1/contacts'
    | '/api/public/v1/docs'
    | '/api/public/v1/openapi.json'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/api/public/v1/contacts/$id'
    | '/api/public/webchat/$widgetId/config'
    | '/api/public/webchat/$widgetId/messages'
    | '/api/public/webchat/$widgetId/session'
    | '/api/public/webchat/$widgetId/upload'
    | '/api/public/webhooks/activecampaign/$accountId'
    | '/api/public/webhooks/hotmart/$accountId'
    | '/api/public/webhooks/sendflow/$accountId'
    | '/api/public/webhooks/shopify/$accountId'
    | '/api/public/v1/automations/$id/trigger'
    | '/api/public/v1/contacts/$id/tags'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/definir-senha'
    | '/docs'
    | '/inbox'
    | '/login'
    | '/pipelines'
    | '/privacidade'
    | '/suporte'
    | '/vendas'
    | '/widget.js'
    | '/admin/agenda'
    | '/admin/api-keys'
    | '/admin/api-logs'
    | '/admin/bases-conhecimento'
    | '/admin/blocklist'
    | '/admin/configuracoes'
    | '/admin/contatos'
    | '/admin/copilot'
    | '/admin/dashboard'
    | '/admin/filas'
    | '/admin/integracoes'
    | '/admin/marcas'
    | '/admin/rastreio'
    | '/admin/stress-test'
    | '/admin/templates'
    | '/admin/usuarios'
    | '/pipelines/$id'
    | '/pipelines/'
    | '/admin/agentes/$id'
    | '/admin/automacoes/$id'
    | '/admin/automacoes/runs'
    | '/admin/broadcasts/$id'
    | '/admin/contatos/importacoes'
    | '/admin/ellie/validations'
    | '/admin/webchat-preview/$widgetId'
    | '/api/public/copilot-chat'
    | '/admin/agentes/'
    | '/admin/automacoes/'
    | '/admin/broadcasts/'
    | '/admin/contatos/'
    | '/api/public/cron/ai-agents-drain'
    | '/api/public/cron/broadcast-drain'
    | '/api/public/cron/broadcast-loop'
    | '/api/public/cron/broadcast-reconcile'
    | '/api/public/cron/broadcast-tick'
    | '/api/public/cron/contact-imports-drain'
    | '/api/public/cron/integrations-drain'
    | '/api/public/cron/integrations-poll'
    | '/api/public/cron/pipeline-activities-tick'
    | '/api/public/hooks/automation-tick'
    | '/api/public/v1/contacts'
    | '/api/public/v1/docs'
    | '/api/public/v1/openapi.json'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/api/public/v1/contacts/$id'
    | '/api/public/webchat/$widgetId/config'
    | '/api/public/webchat/$widgetId/messages'
    | '/api/public/webchat/$widgetId/session'
    | '/api/public/webchat/$widgetId/upload'
    | '/api/public/webhooks/activecampaign/$accountId'
    | '/api/public/webhooks/hotmart/$accountId'
    | '/api/public/webhooks/sendflow/$accountId'
    | '/api/public/webhooks/shopify/$accountId'
    | '/api/public/v1/automations/$id/trigger'
    | '/api/public/v1/contacts/$id/tags'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  DefinirSenhaRoute: typeof DefinirSenhaRoute
  DocsRoute: typeof DocsRoute
  InboxRoute: typeof InboxRoute
  LoginRoute: typeof LoginRoute
  PipelinesRoute: typeof PipelinesRouteWithChildren
  PrivacidadeRoute: typeof PrivacidadeRoute
  SuporteRoute: typeof SuporteRoute
  VendasRoute: typeof VendasRoute
  WidgetDotjsRoute: typeof WidgetDotjsRoute
  AdminAgendaRoute: typeof AdminAgendaRoute
  AdminApiKeysRoute: typeof AdminApiKeysRoute
  AdminApiLogsRoute: typeof AdminApiLogsRoute
  AdminBasesConhecimentoRoute: typeof AdminBasesConhecimentoRoute
  AdminBlocklistRoute: typeof AdminBlocklistRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminContatosRoute: typeof AdminContatosRouteWithChildren
  AdminCopilotRoute: typeof AdminCopilotRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminFilasRoute: typeof AdminFilasRoute
  AdminIntegracoesRoute: typeof AdminIntegracoesRoute
  AdminMarcasRoute: typeof AdminMarcasRoute
  AdminRastreioRoute: typeof AdminRastreioRoute
  AdminStressTestRoute: typeof AdminStressTestRoute
  AdminTemplatesRoute: typeof AdminTemplatesRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminAgentesIdRoute: typeof AdminAgentesIdRoute
  AdminAutomacoesIdRoute: typeof AdminAutomacoesIdRoute
  AdminAutomacoesRunsRoute: typeof AdminAutomacoesRunsRoute
  AdminBroadcastsIdRoute: typeof AdminBroadcastsIdRoute
  AdminEllieValidationsRoute: typeof AdminEllieValidationsRoute
  AdminWebchatPreviewWidgetIdRoute: typeof AdminWebchatPreviewWidgetIdRoute
  ApiPublicCopilotChatRoute: typeof ApiPublicCopilotChatRoute
  AdminAgentesIndexRoute: typeof AdminAgentesIndexRoute
  AdminAutomacoesIndexRoute: typeof AdminAutomacoesIndexRoute
  AdminBroadcastsIndexRoute: typeof AdminBroadcastsIndexRoute
  ApiPublicCronAiAgentsDrainRoute: typeof ApiPublicCronAiAgentsDrainRoute
  ApiPublicCronBroadcastDrainRoute: typeof ApiPublicCronBroadcastDrainRoute
  ApiPublicCronBroadcastLoopRoute: typeof ApiPublicCronBroadcastLoopRoute
  ApiPublicCronBroadcastReconcileRoute: typeof ApiPublicCronBroadcastReconcileRoute
  ApiPublicCronBroadcastTickRoute: typeof ApiPublicCronBroadcastTickRoute
  ApiPublicCronContactImportsDrainRoute: typeof ApiPublicCronContactImportsDrainRoute
  ApiPublicCronIntegrationsDrainRoute: typeof ApiPublicCronIntegrationsDrainRoute
  ApiPublicCronIntegrationsPollRoute: typeof ApiPublicCronIntegrationsPollRoute
  ApiPublicCronPipelineActivitiesTickRoute: typeof ApiPublicCronPipelineActivitiesTickRoute
  ApiPublicHooksAutomationTickRoute: typeof ApiPublicHooksAutomationTickRoute
  ApiPublicV1ContactsRoute: typeof ApiPublicV1ContactsRouteWithChildren
  ApiPublicV1DocsRoute: typeof ApiPublicV1DocsRoute
  ApiPublicV1OpenapiDotjsonRoute: typeof ApiPublicV1OpenapiDotjsonRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  ApiPublicWebchatWidgetIdConfigRoute: typeof ApiPublicWebchatWidgetIdConfigRoute
  ApiPublicWebchatWidgetIdMessagesRoute: typeof ApiPublicWebchatWidgetIdMessagesRoute
  ApiPublicWebchatWidgetIdSessionRoute: typeof ApiPublicWebchatWidgetIdSessionRoute
  ApiPublicWebchatWidgetIdUploadRoute: typeof ApiPublicWebchatWidgetIdUploadRoute
  ApiPublicWebhooksActivecampaignAccountIdRoute: typeof ApiPublicWebhooksActivecampaignAccountIdRoute
  ApiPublicWebhooksHotmartAccountIdRoute: typeof ApiPublicWebhooksHotmartAccountIdRoute
  ApiPublicWebhooksSendflowAccountIdRoute: typeof ApiPublicWebhooksSendflowAccountIdRoute
  ApiPublicWebhooksShopifyAccountIdRoute: typeof ApiPublicWebhooksShopifyAccountIdRoute
  ApiPublicV1AutomationsIdTriggerRoute: typeof ApiPublicV1AutomationsIdTriggerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/widget.js': {
      id: '/widget.js'
      path: '/widget.js'
      fullPath: '/widget.js'
      preLoaderRoute: typeof WidgetDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas': {
      id: '/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof VendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipelines': {
      id: '/pipelines'
      path: '/pipelines'
      fullPath: '/pipelines'
      preLoaderRoute: typeof PipelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/definir-senha': {
      id: '/definir-senha'
      path: '/definir-senha'
      fullPath: '/definir-senha'
      preLoaderRoute: typeof DefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipelines/': {
      id: '/pipelines/'
      path: '/'
      fullPath: '/pipelines/'
      preLoaderRoute: typeof PipelinesIndexRouteImport
      parentRoute: typeof PipelinesRoute
    }
    '/pipelines/$id': {
      id: '/pipelines/$id'
      path: '/$id'
      fullPath: '/pipelines/$id'
      preLoaderRoute: typeof PipelinesIdRouteImport
      parentRoute: typeof PipelinesRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/admin/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/templates': {
      id: '/admin/templates'
      path: '/admin/templates'
      fullPath: '/admin/templates'
      preLoaderRoute: typeof AdminTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/stress-test': {
      id: '/admin/stress-test'
      path: '/admin/stress-test'
      fullPath: '/admin/stress-test'
      preLoaderRoute: typeof AdminStressTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rastreio': {
      id: '/admin/rastreio'
      path: '/admin/rastreio'
      fullPath: '/admin/rastreio'
      preLoaderRoute: typeof AdminRastreioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/marcas': {
      id: '/admin/marcas'
      path: '/admin/marcas'
      fullPath: '/admin/marcas'
      preLoaderRoute: typeof AdminMarcasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/integracoes': {
      id: '/admin/integracoes'
      path: '/admin/integracoes'
      fullPath: '/admin/integracoes'
      preLoaderRoute: typeof AdminIntegracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/filas': {
      id: '/admin/filas'
      path: '/admin/filas'
      fullPath: '/admin/filas'
      preLoaderRoute: typeof AdminFilasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/copilot': {
      id: '/admin/copilot'
      path: '/admin/copilot'
      fullPath: '/admin/copilot'
      preLoaderRoute: typeof AdminCopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contatos': {
      id: '/admin/contatos'
      path: '/admin/contatos'
      fullPath: '/admin/contatos'
      preLoaderRoute: typeof AdminContatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/admin/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blocklist': {
      id: '/admin/blocklist'
      path: '/admin/blocklist'
      fullPath: '/admin/blocklist'
      preLoaderRoute: typeof AdminBlocklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bases-conhecimento': {
      id: '/admin/bases-conhecimento'
      path: '/admin/bases-conhecimento'
      fullPath: '/admin/bases-conhecimento'
      preLoaderRoute: typeof AdminBasesConhecimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/api-logs': {
      id: '/admin/api-logs'
      path: '/admin/api-logs'
      fullPath: '/admin/api-logs'
      preLoaderRoute: typeof AdminApiLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/api-keys': {
      id: '/admin/api-keys'
      path: '/admin/api-keys'
      fullPath: '/admin/api-keys'
      preLoaderRoute: typeof AdminApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/agenda': {
      id: '/admin/agenda'
      path: '/admin/agenda'
      fullPath: '/admin/agenda'
      preLoaderRoute: typeof AdminAgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contatos/': {
      id: '/admin/contatos/'
      path: '/'
      fullPath: '/admin/contatos/'
      preLoaderRoute: typeof AdminContatosIndexRouteImport
      parentRoute: typeof AdminContatosRoute
    }
    '/admin/broadcasts/': {
      id: '/admin/broadcasts/'
      path: '/admin/broadcasts'
      fullPath: '/admin/broadcasts/'
      preLoaderRoute: typeof AdminBroadcastsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/automacoes/': {
      id: '/admin/automacoes/'
      path: '/admin/automacoes'
      fullPath: '/admin/automacoes/'
      preLoaderRoute: typeof AdminAutomacoesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/agentes/': {
      id: '/admin/agentes/'
      path: '/admin/agentes'
      fullPath: '/admin/agentes/'
      preLoaderRoute: typeof AdminAgentesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/copilot-chat': {
      id: '/api/public/copilot-chat'
      path: '/api/public/copilot-chat'
      fullPath: '/api/public/copilot-chat'
      preLoaderRoute: typeof ApiPublicCopilotChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/webchat-preview/$widgetId': {
      id: '/admin/webchat-preview/$widgetId'
      path: '/admin/webchat-preview/$widgetId'
      fullPath: '/admin/webchat-preview/$widgetId'
      preLoaderRoute: typeof AdminWebchatPreviewWidgetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ellie/validations': {
      id: '/admin/ellie/validations'
      path: '/admin/ellie/validations'
      fullPath: '/admin/ellie/validations'
      preLoaderRoute: typeof AdminEllieValidationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contatos/importacoes': {
      id: '/admin/contatos/importacoes'
      path: '/importacoes'
      fullPath: '/admin/contatos/importacoes'
      preLoaderRoute: typeof AdminContatosImportacoesRouteImport
      parentRoute: typeof AdminContatosRoute
    }
    '/admin/broadcasts/$id': {
      id: '/admin/broadcasts/$id'
      path: '/admin/broadcasts/$id'
      fullPath: '/admin/broadcasts/$id'
      preLoaderRoute: typeof AdminBroadcastsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/automacoes/runs': {
      id: '/admin/automacoes/runs'
      path: '/admin/automacoes/runs'
      fullPath: '/admin/automacoes/runs'
      preLoaderRoute: typeof AdminAutomacoesRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/automacoes/$id': {
      id: '/admin/automacoes/$id'
      path: '/admin/automacoes/$id'
      fullPath: '/admin/automacoes/$id'
      preLoaderRoute: typeof AdminAutomacoesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/agentes/$id': {
      id: '/admin/agentes/$id'
      path: '/admin/agentes/$id'
      fullPath: '/admin/agentes/$id'
      preLoaderRoute: typeof AdminAgentesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/openapi.json': {
      id: '/api/public/v1/openapi.json'
      path: '/api/public/v1/openapi.json'
      fullPath: '/api/public/v1/openapi.json'
      preLoaderRoute: typeof ApiPublicV1OpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/docs': {
      id: '/api/public/v1/docs'
      path: '/api/public/v1/docs'
      fullPath: '/api/public/v1/docs'
      preLoaderRoute: typeof ApiPublicV1DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/contacts': {
      id: '/api/public/v1/contacts'
      path: '/api/public/v1/contacts'
      fullPath: '/api/public/v1/contacts'
      preLoaderRoute: typeof ApiPublicV1ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/automation-tick': {
      id: '/api/public/hooks/automation-tick'
      path: '/api/public/hooks/automation-tick'
      fullPath: '/api/public/hooks/automation-tick'
      preLoaderRoute: typeof ApiPublicHooksAutomationTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/pipeline-activities-tick': {
      id: '/api/public/cron/pipeline-activities-tick'
      path: '/api/public/cron/pipeline-activities-tick'
      fullPath: '/api/public/cron/pipeline-activities-tick'
      preLoaderRoute: typeof ApiPublicCronPipelineActivitiesTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/integrations-poll': {
      id: '/api/public/cron/integrations-poll'
      path: '/api/public/cron/integrations-poll'
      fullPath: '/api/public/cron/integrations-poll'
      preLoaderRoute: typeof ApiPublicCronIntegrationsPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/integrations-drain': {
      id: '/api/public/cron/integrations-drain'
      path: '/api/public/cron/integrations-drain'
      fullPath: '/api/public/cron/integrations-drain'
      preLoaderRoute: typeof ApiPublicCronIntegrationsDrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/contact-imports-drain': {
      id: '/api/public/cron/contact-imports-drain'
      path: '/api/public/cron/contact-imports-drain'
      fullPath: '/api/public/cron/contact-imports-drain'
      preLoaderRoute: typeof ApiPublicCronContactImportsDrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/broadcast-tick': {
      id: '/api/public/cron/broadcast-tick'
      path: '/api/public/cron/broadcast-tick'
      fullPath: '/api/public/cron/broadcast-tick'
      preLoaderRoute: typeof ApiPublicCronBroadcastTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/broadcast-reconcile': {
      id: '/api/public/cron/broadcast-reconcile'
      path: '/api/public/cron/broadcast-reconcile'
      fullPath: '/api/public/cron/broadcast-reconcile'
      preLoaderRoute: typeof ApiPublicCronBroadcastReconcileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/broadcast-loop': {
      id: '/api/public/cron/broadcast-loop'
      path: '/api/public/cron/broadcast-loop'
      fullPath: '/api/public/cron/broadcast-loop'
      preLoaderRoute: typeof ApiPublicCronBroadcastLoopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/broadcast-drain': {
      id: '/api/public/cron/broadcast-drain'
      path: '/api/public/cron/broadcast-drain'
      fullPath: '/api/public/cron/broadcast-drain'
      preLoaderRoute: typeof ApiPublicCronBroadcastDrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/ai-agents-drain': {
      id: '/api/public/cron/ai-agents-drain'
      path: '/api/public/cron/ai-agents-drain'
      fullPath: '/api/public/cron/ai-agents-drain'
      preLoaderRoute: typeof ApiPublicCronAiAgentsDrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/shopify/$accountId': {
      id: '/api/public/webhooks/shopify/$accountId'
      path: '/api/public/webhooks/shopify/$accountId'
      fullPath: '/api/public/webhooks/shopify/$accountId'
      preLoaderRoute: typeof ApiPublicWebhooksShopifyAccountIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/sendflow/$accountId': {
      id: '/api/public/webhooks/sendflow/$accountId'
      path: '/api/public/webhooks/sendflow/$accountId'
      fullPath: '/api/public/webhooks/sendflow/$accountId'
      preLoaderRoute: typeof ApiPublicWebhooksSendflowAccountIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/hotmart/$accountId': {
      id: '/api/public/webhooks/hotmart/$accountId'
      path: '/api/public/webhooks/hotmart/$accountId'
      fullPath: '/api/public/webhooks/hotmart/$accountId'
      preLoaderRoute: typeof ApiPublicWebhooksHotmartAccountIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/activecampaign/$accountId': {
      id: '/api/public/webhooks/activecampaign/$accountId'
      path: '/api/public/webhooks/activecampaign/$accountId'
      fullPath: '/api/public/webhooks/activecampaign/$accountId'
      preLoaderRoute: typeof ApiPublicWebhooksActivecampaignAccountIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webchat/$widgetId/upload': {
      id: '/api/public/webchat/$widgetId/upload'
      path: '/api/public/webchat/$widgetId/upload'
      fullPath: '/api/public/webchat/$widgetId/upload'
      preLoaderRoute: typeof ApiPublicWebchatWidgetIdUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webchat/$widgetId/session': {
      id: '/api/public/webchat/$widgetId/session'
      path: '/api/public/webchat/$widgetId/session'
      fullPath: '/api/public/webchat/$widgetId/session'
      preLoaderRoute: typeof ApiPublicWebchatWidgetIdSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webchat/$widgetId/messages': {
      id: '/api/public/webchat/$widgetId/messages'
      path: '/api/public/webchat/$widgetId/messages'
      fullPath: '/api/public/webchat/$widgetId/messages'
      preLoaderRoute: typeof ApiPublicWebchatWidgetIdMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webchat/$widgetId/config': {
      id: '/api/public/webchat/$widgetId/config'
      path: '/api/public/webchat/$widgetId/config'
      fullPath: '/api/public/webchat/$widgetId/config'
      preLoaderRoute: typeof ApiPublicWebchatWidgetIdConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/contacts/$id': {
      id: '/api/public/v1/contacts/$id'
      path: '/$id'
      fullPath: '/api/public/v1/contacts/$id'
      preLoaderRoute: typeof ApiPublicV1ContactsIdRouteImport
      parentRoute: typeof ApiPublicV1ContactsRoute
    }
    '/api/public/v1/contacts/$id/tags': {
      id: '/api/public/v1/contacts/$id/tags'
      path: '/tags'
      fullPath: '/api/public/v1/contacts/$id/tags'
      preLoaderRoute: typeof ApiPublicV1ContactsIdTagsRouteImport
      parentRoute: typeof ApiPublicV1ContactsIdRoute
    }
    '/api/public/v1/automations/$id/trigger': {
      id: '/api/public/v1/automations/$id/trigger'
      path: '/api/public/v1/automations/$id/trigger'
      fullPath: '/api/public/v1/automations/$id/trigger'
      preLoaderRoute: typeof ApiPublicV1AutomationsIdTriggerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PipelinesRouteChildren {
  PipelinesIdRoute: typeof PipelinesIdRoute
  PipelinesIndexRoute: typeof PipelinesIndexRoute
}

const PipelinesRouteChildren: PipelinesRouteChildren = {
  PipelinesIdRoute: PipelinesIdRoute,
  PipelinesIndexRoute: PipelinesIndexRoute,
}

const PipelinesRouteWithChildren = PipelinesRoute._addFileChildren(
  PipelinesRouteChildren,
)

interface AdminContatosRouteChildren {
  AdminContatosImportacoesRoute: typeof AdminContatosImportacoesRoute
  AdminContatosIndexRoute: typeof AdminContatosIndexRoute
}

const AdminContatosRouteChildren: AdminContatosRouteChildren = {
  AdminContatosImportacoesRoute: AdminContatosImportacoesRoute,
  AdminContatosIndexRoute: AdminContatosIndexRoute,
}

const AdminContatosRouteWithChildren = AdminContatosRoute._addFileChildren(
  AdminContatosRouteChildren,
)

interface ApiPublicV1ContactsIdRouteChildren {
  ApiPublicV1ContactsIdTagsRoute: typeof ApiPublicV1ContactsIdTagsRoute
}

const ApiPublicV1ContactsIdRouteChildren: ApiPublicV1ContactsIdRouteChildren = {
  ApiPublicV1ContactsIdTagsRoute: ApiPublicV1ContactsIdTagsRoute,
}

const ApiPublicV1ContactsIdRouteWithChildren =
  ApiPublicV1ContactsIdRoute._addFileChildren(
    ApiPublicV1ContactsIdRouteChildren,
  )

interface ApiPublicV1ContactsRouteChildren {
  ApiPublicV1ContactsIdRoute: typeof ApiPublicV1ContactsIdRouteWithChildren
}

const ApiPublicV1ContactsRouteChildren: ApiPublicV1ContactsRouteChildren = {
  ApiPublicV1ContactsIdRoute: ApiPublicV1ContactsIdRouteWithChildren,
}

const ApiPublicV1ContactsRouteWithChildren =
  ApiPublicV1ContactsRoute._addFileChildren(ApiPublicV1ContactsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  DefinirSenhaRoute: DefinirSenhaRoute,
  DocsRoute: DocsRoute,
  InboxRoute: InboxRoute,
  LoginRoute: LoginRoute,
  PipelinesRoute: PipelinesRouteWithChildren,
  PrivacidadeRoute: PrivacidadeRoute,
  SuporteRoute: SuporteRoute,
  VendasRoute: VendasRoute,
  WidgetDotjsRoute: WidgetDotjsRoute,
  AdminAgendaRoute: AdminAgendaRoute,
  AdminApiKeysRoute: AdminApiKeysRoute,
  AdminApiLogsRoute: AdminApiLogsRoute,
  AdminBasesConhecimentoRoute: AdminBasesConhecimentoRoute,
  AdminBlocklistRoute: AdminBlocklistRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminContatosRoute: AdminContatosRouteWithChildren,
  AdminCopilotRoute: AdminCopilotRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminFilasRoute: AdminFilasRoute,
  AdminIntegracoesRoute: AdminIntegracoesRoute,
  AdminMarcasRoute: AdminMarcasRoute,
  AdminRastreioRoute: AdminRastreioRoute,
  AdminStressTestRoute: AdminStressTestRoute,
  AdminTemplatesRoute: AdminTemplatesRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminAgentesIdRoute: AdminAgentesIdRoute,
  AdminAutomacoesIdRoute: AdminAutomacoesIdRoute,
  AdminAutomacoesRunsRoute: AdminAutomacoesRunsRoute,
  AdminBroadcastsIdRoute: AdminBroadcastsIdRoute,
  AdminEllieValidationsRoute: AdminEllieValidationsRoute,
  AdminWebchatPreviewWidgetIdRoute: AdminWebchatPreviewWidgetIdRoute,
  ApiPublicCopilotChatRoute: ApiPublicCopilotChatRoute,
  AdminAgentesIndexRoute: AdminAgentesIndexRoute,
  AdminAutomacoesIndexRoute: AdminAutomacoesIndexRoute,
  AdminBroadcastsIndexRoute: AdminBroadcastsIndexRoute,
  ApiPublicCronAiAgentsDrainRoute: ApiPublicCronAiAgentsDrainRoute,
  ApiPublicCronBroadcastDrainRoute: ApiPublicCronBroadcastDrainRoute,
  ApiPublicCronBroadcastLoopRoute: ApiPublicCronBroadcastLoopRoute,
  ApiPublicCronBroadcastReconcileRoute: ApiPublicCronBroadcastReconcileRoute,
  ApiPublicCronBroadcastTickRoute: ApiPublicCronBroadcastTickRoute,
  ApiPublicCronContactImportsDrainRoute: ApiPublicCronContactImportsDrainRoute,
  ApiPublicCronIntegrationsDrainRoute: ApiPublicCronIntegrationsDrainRoute,
  ApiPublicCronIntegrationsPollRoute: ApiPublicCronIntegrationsPollRoute,
  ApiPublicCronPipelineActivitiesTickRoute:
    ApiPublicCronPipelineActivitiesTickRoute,
  ApiPublicHooksAutomationTickRoute: ApiPublicHooksAutomationTickRoute,
  ApiPublicV1ContactsRoute: ApiPublicV1ContactsRouteWithChildren,
  ApiPublicV1DocsRoute: ApiPublicV1DocsRoute,
  ApiPublicV1OpenapiDotjsonRoute: ApiPublicV1OpenapiDotjsonRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  ApiPublicWebchatWidgetIdConfigRoute: ApiPublicWebchatWidgetIdConfigRoute,
  ApiPublicWebchatWidgetIdMessagesRoute: ApiPublicWebchatWidgetIdMessagesRoute,
  ApiPublicWebchatWidgetIdSessionRoute: ApiPublicWebchatWidgetIdSessionRoute,
  ApiPublicWebchatWidgetIdUploadRoute: ApiPublicWebchatWidgetIdUploadRoute,
  ApiPublicWebhooksActivecampaignAccountIdRoute:
    ApiPublicWebhooksActivecampaignAccountIdRoute,
  ApiPublicWebhooksHotmartAccountIdRoute:
    ApiPublicWebhooksHotmartAccountIdRoute,
  ApiPublicWebhooksSendflowAccountIdRoute:
    ApiPublicWebhooksSendflowAccountIdRoute,
  ApiPublicWebhooksShopifyAccountIdRoute:
    ApiPublicWebhooksShopifyAccountIdRoute,
  ApiPublicV1AutomationsIdTriggerRoute: ApiPublicV1AutomationsIdTriggerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
